version: "3.9"
services:
  redis-server-container:
    image: redis_server_image:latest
    container_name: redis-server-container
    networks:
      - redis-net
  redis-cli-container:
    image: redis_cli_image:latest
    container_name: redis-cli-container
    depends_on:
      - redis-server-container
    networks:
      - redis-net
    entrypoint: ["sleep"]
    command: ["infinity"]
    tty: true
    stdin_open: true
networks:
  redis-net:
    driver: bridge
